package com.nubeero.cia.reinsurance;

import com.nubeero.cia.common.api.ApiResponse;
import com.nubeero.cia.reinsurance.dto.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/ri/fac-covers")
@Tag(name = "Facultative Reinsurance Covers",
     description = "Facultative (FAC) outward covers — for risks that exceed treaty gross capacity or aren't covered by treaty. State machine: DRAFT → CONFIRMED → CANCELLED. Confirmation triggers FAC_PREMIUM_CEDED event → SubledgerPostingService cascades a CreditNote (payable to reinsurer) + JE.")
@SecurityRequirement(name = "bearer-jwt")
@RequiredArgsConstructor
public class RiFacCoverController {

    private final FacCoverService service;

    @GetMapping
    @PreAuthorize("hasRole('REINSURANCE_VIEW')")
    @Operation(summary = "List FAC covers (paginated, filterable)",
               description = "Filter by policyId, status, and/or reinsuranceCompanyId. Used by the FAC dashboard to show outstanding offer slips per reinsurer.")
    @ApiResponses({
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "FAC cover page",
            content = @Content(schema = @Schema(implementation = FacCoverResponse.class))),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Forbidden — caller lacks REINSURANCE_VIEW", content = @Content)
    })
    public ApiResponse<List<FacCoverResponse>> list(
            @RequestParam(required = false) UUID policyId,
            @RequestParam(required = false) FacCoverStatus status,
            @RequestParam(required = false) UUID reinsuranceCompanyId,
            @PageableDefault(size = 20) Pageable pageable) {
        return ApiResponse.success(
                service.list(policyId, status, reinsuranceCompanyId, pageable).map(this::toResponse).getContent());
    }

    @GetMapping("/{id}")
    @PreAuthorize("hasRole('REINSURANCE_VIEW')")
    @Operation(summary = "Get FAC cover detail")
    @ApiResponses({
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "FAC cover found",
            content = @Content(schema = @Schema(implementation = FacCoverResponse.class))),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Forbidden — caller lacks REINSURANCE_VIEW", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "FAC cover not found", content = @Content)
    })
    public ApiResponse<FacCoverResponse> get(@PathVariable UUID id) {
        return ApiResponse.success(toResponse(service.findOrThrow(id)));
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @PreAuthorize("hasRole('REINSURANCE_CREATE')")
    @Operation(summary = "Create a FAC cover (DRAFT)",
               description = "Generates an offer slip reference (facReference) and DRAFT-state cover. The offer slip PDF is generated by cia-documents and sent to the reinsurer. Confirmation comes later via /confirm.")
    @ApiResponses({
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "201", description = "FAC cover created",
            content = @Content(schema = @Schema(implementation = FacCoverResponse.class))),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "Validation error (negative premium, dates inverted, reinsurer inactive)", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Forbidden — caller lacks REINSURANCE_CREATE", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "Policy or reinsurance company not found", content = @Content)
    })
    public ApiResponse<FacCoverResponse> create(@Valid @RequestBody CreateFacCoverRequest req) {
        return ApiResponse.success(toResponse(service.create(req)));
    }

    @PostMapping("/{id}/confirm")
    @PreAuthorize("hasRole('REINSURANCE_APPROVE')")
    @Operation(summary = "Confirm FAC cover (reinsurer accepted)",
               description = "Transitions DRAFT → CONFIRMED. Fires FAC_PREMIUM_CEDED event → SubledgerPostingService cascades a CreditNote (payable to the reinsurer for ceded premium net of commission) + JE. Period-lock check applies.")
    @ApiResponses({
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "FAC cover confirmed",
            content = @Content(schema = @Schema(implementation = FacCoverResponse.class))),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Forbidden — caller lacks REINSURANCE_APPROVE", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "FAC cover not found", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "409", description = "FAC cover not in DRAFT state", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "423", description = "Target period is closed", content = @Content)
    })
    public ApiResponse<FacCoverResponse> confirm(@PathVariable UUID id) {
        return ApiResponse.success(toResponse(service.confirm(id)));
    }

    @PostMapping("/{id}/cancel")
    @PreAuthorize("hasRole('REINSURANCE_UPDATE')")
    @Operation(summary = "Cancel a FAC cover",
               description = "Cancels with a mandatory reason. For CONFIRMED covers, reverses the cascaded credit note + JE (reversal carve-out applies — can cross a closed period).")
    @ApiResponses({
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "FAC cover cancelled",
            content = @Content(schema = @Schema(implementation = FacCoverResponse.class))),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "Reason missing", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Forbidden — caller lacks REINSURANCE_UPDATE", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "FAC cover not found", content = @Content),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "409", description = "FAC cover already in terminal state", content = @Content)
    })
    public ApiResponse<FacCoverResponse> cancel(
            @PathVariable UUID id,
            @Valid @RequestBody CancelFacCoverRequest req) {
        return ApiResponse.success(toResponse(service.cancel(id, req.reason())));
    }

    // ─── Mapping ──────────────────────────────────────────────────────────

    private FacCoverResponse toResponse(RiFacCover f) {
        return new FacCoverResponse(
                f.getId(), f.getFacReference(),
                f.getPolicyId(), f.getPolicyNumber(),
                f.getReinsuranceCompanyId(), f.getReinsuranceCompanyName(),
                f.getStatus(),
                f.getSumInsuredCeded(), f.getPremiumRate(), f.getPremiumCeded(),
                f.getCommissionRate(), f.getCommissionAmount(), f.getNetPremium(),
                f.getCurrencyCode(), f.getCoverFrom(), f.getCoverTo(),
                f.getOfferSlipReference(), f.getTerms(),
                f.getApprovedBy(), f.getApprovedAt(),
                f.getCancelledBy(), f.getCancelledAt(), f.getCancellationReason(),
                f.getCreatedAt()
        );
    }
}
