package com.nubeero.cia.api.finance.pdf;

import com.nubeero.cia.api.finance.FinanceItSupport;
import com.nubeero.cia.documents.HtmlToPdfConverter;
import com.nubeero.cia.finance.DebitNote;
import com.nubeero.cia.finance.DebitNoteStatus;
import com.nubeero.cia.finance.FinanceEntityType;
import com.nubeero.cia.finance.PaymentMethod;
import com.nubeero.cia.finance.Receipt;
import com.nubeero.cia.finance.TransactionStatus;
import com.nubeero.cia.finance.pdf.ReceiptPdfGenerator;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration;
import org.springframework.context.annotation.Import;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Pins {@link ReceiptPdfGenerator} contract:
 * <ul>
 *   <li>Generated bytes parse cleanly as a PDF.</li>
 *   <li>Receipt number, DN number, customer name, ₦ amount, method all present.</li>
 *   <li>Policy number row renders only when the DN is policy-backed.</li>
 *   <li>Narration appears in the body.</li>
 * </ul>
 *
 * @since Slice β — Task 10, F7 receipt + payment-voucher PDF generation
 */
@Import({
    com.nubeero.cia.common.config.CiaCommonAutoConfiguration.class,
    ThymeleafAutoConfiguration.class,
    HtmlToPdfConverter.class,
    ReceiptPdfGenerator.class
})
class ReceiptPdfGeneratorIT extends FinanceItSupport {

    @Autowired ReceiptPdfGenerator generator;

    @Test
    @DisplayName("Generated PDF parses via PDFBox and contains receipt fields + ₦")
    void generatesParseablePdfWithExpectedContent() throws Exception {
        Receipt r = sampleReceipt();

        byte[] pdf = generator.generate(r);
        assertThat(pdf).isNotEmpty();

        try (PDDocument doc = Loader.loadPDF(pdf)) {
            String text = new PDFTextStripper().getText(doc);
            assertThat(text)
                .contains("OFFICIAL RECEIPT")
                .contains(r.getReceiptNumber())
                .contains(r.getDebitNote().getDebitNoteNumber())
                .contains("Adaeze Okonkwo")
                .contains("₦250,000.00")
                .contains("BANK TRANSFER");
        }
    }

    @Test
    @DisplayName("Generator returns null cleanly when receipt has no debitNote (NPE in template)")
    void returnsNullOnRenderingException() {
        Receipt broken = new Receipt();
        broken.setReceiptNumber("REC-IT-BROKEN");
        broken.setAmount(new BigDecimal("100"));
        broken.setPaymentDate(LocalDate.now());
        broken.setPaymentMethod(PaymentMethod.CASH);
        broken.setStatus(TransactionStatus.POSTED);
        // No debitNote → template's getCustomerName() will NPE

        byte[] result = generator.generate(broken);

        assertThat(result)
            .as("Generator must never throw; null signals to ReceiptService.post() to leave pdf_path unset")
            .isNull();
    }

    @Test
    @DisplayName("Policy number row renders when DN.entityType == POLICY")
    void rendersPolicyNumberRowWhenDnIsPolicyBacked() throws Exception {
        Receipt r = sampleReceipt(); // sampleReceipt's DN is POLICY-backed
        assertThat(r.getDebitNote().getEntityType()).isEqualTo(FinanceEntityType.POLICY);

        byte[] pdf = generator.generate(r);
        try (PDDocument doc = Loader.loadPDF(pdf)) {
            String text = new PDFTextStripper().getText(doc);
            assertThat(text).contains(r.getDebitNote().getEntityReference());
        }
    }

    @Test
    @DisplayName("Narration appears in the 'Being payment for' section")
    void narrationRenders() throws Exception {
        Receipt r = sampleReceipt();
        r.setNarration("Q1 2026 premium settlement");

        byte[] pdf = generator.generate(r);
        try (PDDocument doc = Loader.loadPDF(pdf)) {
            String text = new PDFTextStripper().getText(doc);
            assertThat(text).contains("Q1 2026 premium settlement");
        }
    }

    private Receipt sampleReceipt() {
        DebitNote dn = new DebitNote();
        dn.setDebitNoteNumber("DN-IT-2026-00042");
        dn.setStatus(DebitNoteStatus.PARTIAL);
        dn.setEntityType(FinanceEntityType.POLICY);
        dn.setEntityId(UUID.randomUUID());
        dn.setEntityReference("POL-IT-2026-001");
        dn.setCustomerId(UUID.randomUUID());
        dn.setCustomerName("Adaeze Okonkwo");
        dn.setDescription("Premium for policy POL-IT-2026-001");
        dn.setAmount(new BigDecimal("500000.00"));
        dn.setTotalAmount(new BigDecimal("500000.00"));

        Receipt r = new Receipt();
        r.setReceiptNumber("REC-IT-2026-00001");
        r.setDebitNote(dn);
        r.setAmount(new BigDecimal("250000.00"));
        r.setPaymentDate(LocalDate.now());
        r.setPaymentMethod(PaymentMethod.BANK_TRANSFER);
        r.setStatus(TransactionStatus.POSTED);
        r.setNarration("Partial premium");
        r.setPostedBy("alice");
        return r;
    }
}
